### ISSUE TITLE
Icon request: Notifications Bell

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-icons#126]
### Use case

For notifications icon in a typical Modus navbar

### Example image

![image](https://user-images.githubusercontent.com/1212885/218467436-2f9305f8-13d7-453b-8407-5f4cd0c6ff23.png)

from: https://fonts.google.com/icons?icon.query=notification

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] I have [searched for existing issues](https://github.com/trimble-oss/modus-icons/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)

**Comment by soniakaukonen** [comment]
![notifications](https://user-images.githubusercontent.com/101354258/219587982-c8c40b11-df21-478f-9da0-ba4c9ba7f986.svg)
 solid

**Comment by soniakaukonen** [comment]
![notifications](https://user-images.githubusercontent.com/101354258/219588108-654d17ae-cf1c-4886-807c-cc604fc2c20f.svg)
 outlined

**Comment by soniakaukonen** [comment]
Notifications off solid

![Image](https://user-images.githubusercontent.com/101354258/220268694-560eeb2f-1d5c-4165-b319-c4adb68b35b0.svg)

**Comment by soniakaukonen** [comment]
![Image](https://user-images.githubusercontent.com/101354258/220268905-99143ab9-720b-4455-a65a-8dfaa493e947.svg)

Notifications off outline

@coliff now complete.
