### ISSUE TITLE
Broken Address webfont icon (Modus Outlined)

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-icons#142]
The Address icon isn't displaying correctly as webfont. See examples here:
https://modus-icons.trimble.com/modus-outlined/address/

Modus Outlined webfont cheat sheet here:
https://modus-icons.trimble.com/modus-outlined/fonts/modus-icons.html

It looks like the icons SVG code hasn't been flattened properly, or maybe it's the user of `fill-rule="evenodd"` being problematic?

**Comment by soniakaukonen** [comment]
![address](https://user-images.githubusercontent.com/101354258/219627153-120133ea-f7d7-49c0-9106-a00b1489dc38.svg)

Try now.

**Comment by soniakaukonen** [comment]
Compound path in the former did not look right either:. Good catch!
![image](https://user-images.githubusercontent.com/101354258/219628865-242e8aae-0035-4930-98ca-c86bee9e4952.png)

**Comment by coliff** [comment]
Great! Thanks, that works - just tested locally.
![image](https://user-images.githubusercontent.com/1212885/219652856-51e0b077-3b56-450e-b0af-5f8dbf876262.png)
I'll make a PR for it.

**Comment by soniakaukonen** [comment]
That was the problem:

![image](https://user-images.githubusercontent.com/101354258/219658414-cb866d63-8b95-429d-8ca7-9049da36e5f3.png)

Will replace in the native .ai file
