### ISSUE TITLE
Icon request: Doc Spreadsheet

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-icons#261]
### Use case

For uploading a CSV or similar spreadsheet file.

### Example image

![image](https://github.com/trimble-oss/modus-icons/assets/1212885/d9c5c0d9-ec33-449e-ad06-ab92472328e4)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] I have [searched for existing issues](https://github.com/trimble-oss/modus-icons/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)

**Comment by soniakaukonen** [comment]
Covered by icon additions item https://github.com/trimble-oss/modus-icons/issues/266

**Comment by coliff** [comment]
You don't need to add a new GitHub issue for any icons we are adding as it just adds unnecessary noise.

Issues should just be added for icon requests, bugs and web site feature requests etc
