### ISSUE TITLE
Transportation Set - Icon Requests

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-icons#387]
The Maps Toolbox site currently uses Material Icons for some icons, and Modus Icons for the rest. It'd be great to just use Modus Icons but to do that we'd need icons for the following added:

**Layer Icons:** (should prefix the filenames for these icons with `layer_`)

- https://fonts.google.com/icons?icon.query=blur_on `layer_heatmap`
- https://fonts.google.com/icons?icon.query=crop_5_4 `layer_fill`
- https://fonts.google.com/icons?icon.query=hdr_auto `layer_symbol`
- https://fonts.google.com/icons?icon.query=view_module `layer_raster`
- https://fonts.google.com/icons?icon.query=scatter_plot `layer_circle`
- https://fonts.google.com/icons?icon.query=show_chart `layer_line`
- https://fonts.google.com/icons?icon.query=square `layer_background`

**Others:**

- https://fonts.google.com/icons?icon.query=format_indent_increase (should be called `format_code`)
- Expression ( Σ ) `expression`

cc @egunther39 @nspringer-trimble

**Comment by egunther39** [comment]
great, thanks! Arden or myself will work on this

**Comment by egunther39** [comment]
This issue is done. PR created to publish changes
